services:
  - docker
script:
  - docker build -t inseefrlab/rstudio .
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    skip_cleanup: true
    script:
      docker push inseefrlab/rstudio:latest
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      docker tag inseefrlab/rstudio inseefrlab/rstudio:$TRAVIS_TAG && docker push inseefrlab/rstudio:$TRAVIS_TAG
    on:
      tags: true
